// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhh4PmJqK3_ZeAvSIl472qjvCFVkLq5X8',
    appId: '1:208723874073:web:d64d9bf8a62dba8f68f588',
    messagingSenderId: '208723874073',
    projectId: 'learn-flutter-firebase-7dfc5',
    authDomain: 'learn-flutter-firebase-7dfc5.firebaseapp.com',
    storageBucket: 'learn-flutter-firebase-7dfc5.appspot.com',
    measurementId: 'G-PJ5ZX3RVH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOCJZoSo52pDxBCRoGwlADM5G-KAmFe50',
    appId: '1:208723874073:android:61465481b156386168f588',
    messagingSenderId: '208723874073',
    projectId: 'learn-flutter-firebase-7dfc5',
    storageBucket: 'learn-flutter-firebase-7dfc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdTkczIMBb7PbG87Axl7QYM54HX4LTrA0',
    appId: '1:208723874073:ios:14437e49ab533f9968f588',
    messagingSenderId: '208723874073',
    projectId: 'learn-flutter-firebase-7dfc5',
    storageBucket: 'learn-flutter-firebase-7dfc5.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdTkczIMBb7PbG87Axl7QYM54HX4LTrA0',
    appId: '1:208723874073:ios:14437e49ab533f9968f588',
    messagingSenderId: '208723874073',
    projectId: 'learn-flutter-firebase-7dfc5',
    storageBucket: 'learn-flutter-firebase-7dfc5.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhh4PmJqK3_ZeAvSIl472qjvCFVkLq5X8',
    appId: '1:208723874073:web:8b43e7326115ea8f68f588',
    messagingSenderId: '208723874073',
    projectId: 'learn-flutter-firebase-7dfc5',
    authDomain: 'learn-flutter-firebase-7dfc5.firebaseapp.com',
    storageBucket: 'learn-flutter-firebase-7dfc5.appspot.com',
    measurementId: 'G-NY7XJYL2D2',
  );
}
